### PR TITLE
I add free javascript application hosting

### PR DESCRIPTION
**Pull request by jamiuabdulkareem**
It was Heroku alternative

### CODE REVIEW

**Comment by Ismail142** [comment]
the imageName should match an image located in the  **public/assets/Images
/hosting/**.
So provide an image the folder as I have indicated earlier and in the data.json, you set the imgName to that name.

**Comment by jamiuabdulkareem** [comment]
I have fiexed that

**Comment by jamiuabdulkareem** [comment]
I fixed the image

**Comment by jamiuabdulkareem** [comment]
> the imageName should match an image located in the **public/assets/Images /hosting/**. So provide an image the folder as I have indicated earlier and in the data.json, you set the imgName to that name.

I have provide it into the folder

**Pull request merged**
